name: Deploy Fullstack App on EC2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [22.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: |
            bill-backend/package-lock.json
            bill-frontend/app/package-lock.json

      # ------------------------------
      # BACKEND SETUP
      # ------------------------------
      - name: Install backend dependencies
        working-directory: ./bill-backend
        run: npm install

      - name: Create backend .env file
        working-directory: ./bill-backend
        run: |
          touch .env
          echo "${{ secrets.PROD_BACKEND_ENV }}" > .env

      - name: Start backend with PM2
        working-directory: ./bill-backend
        run: |
          /home/ubuntu/.nvm/versions/node/v22.16.0/bin/pm2 restart backend || /home/ubuntu/.nvm/versions/node/v22.16.0/bin/pm2 start index.js --name backend

      # ------------------------------
      # FRONTEND SETUP
      # ------------------------------
      - name: Clean npm cache & remove existing dependencies
        working-directory: ./bill-frontend/app
        run: |
          rm -rf node_modules package-lock.json
          npm cache clean --force

      - name: Install frontend dependencies
        working-directory: ./bill-frontend/app
        run: npm install

      - name: Create frontend .env file
        working-directory: ./bill-frontend/app
        run: |
          touch .env
          echo "${{ secrets.PROD_FRONTEND_ENV }}" > .env

      - name: Build frontend
        working-directory: ./bill-frontend/app
        run: npm run build

      - name: Deploy frontend to Nginx
        run: |
          sudo rm -rf /var/www/html/*
          sudo cp -r ./bill-frontend/app/dist/* /var/www/html/
